spring.datasource.primary:
  url: jdbc:mysql://localhost:3306/test
  username: root
  password: admin
  driver-class-name: com.mysql.jdbc.Driver
  
spring.datasource.secondary:
  url: jdbc:mysql://localhost:3306/test1
  username: root
  password: admin
  driver-class-name: com.mysql.jdbc.Driver


server:
  port: 80